services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
    networks:
      - my-network
    ports:
      - "8080:8080"

  backend:
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    env_file:
      - .env
    ports:
      - "7090:7090"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - my-network

  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - my-network
    command: -p ${DATABASE_PORT}

volumes:
  postgres_data:
networks:
  my-network:
    driver: bridge
